{% set name = "start_jupyter_cm" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 242e60075257478c965205676a6288a9be44ad29beb768396694863196101c75

build:
  number: 0
  entry_points:
    - start_jupyter_cm = start_jupyter_cm.command:_run
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: True  # [osx]
  skip: True  # [py2k]

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - notebook
  imports:
    - start_jupyter_cm
  commands:
    - start_jupyter_cm --help
    - start_jupyter_cm --version
    - start_jupyter_cm
    - start_jupyter_cm --remove

about:
  home: https://github.com/hyperspy/start_jupyter_cm
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Add entries to start Jupyter from context menu.

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
