{% set name = "start_jupyter_cm" %}
{% set version = "1.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1af42a46e5b42e40ffa84f6c8dc211a8094d0a4cf67f6169049775964babac96

build:
  number: 0
  entry_points:
    - jupyter_context-menu_add = start_jupyter_cm:_add
    - jupyter_context-menu_remove = start_jupyter_cm:_remove
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: true  # [osx]
  skip: True  # [py2k]

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - start_jupyter_cm
  commands:
    - jupyter_context-menu_add --help
    - jupyter_context-menu_remove --help

about:
  home: https://github.com/hyperspy/start_jupyter_cm
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Add entries to start Jupyter from context menu.

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
