{% set name = "start_jupyter_cm" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c94c4cb268053199bb6e518b29635750adbf9c67d6ca75fa18c70172d1cf31a

build:
  number: 0
  noarch: python
  entry_points:
    - start_jupyter_cm = start_jupyter_cm.command:_run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - python >=3.3

test:
  requires:
    - notebook
    - pip
  imports:
    - start_jupyter_cm
  commands:
    - pip check
    - start_jupyter_cm --help
    - start_jupyter_cm --version
    - start_jupyter_cm
    - start_jupyter_cm --remove

about:
  home: https://github.com/hyperspy/start_jupyter_cm
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Add entries to start Jupyter from context menu.

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
