{% set name = "start_jupyter_cm" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bda064a6cd1513264ca40f9b52eccf959bd04ba24fbb0cf4bc5acdcd814dee3c

build:
  number: 0
  noarch: python
  entry_points:
    - start_jupyter_cm = start_jupyter_cm.command:_run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - python >=3.3

test:
  requires:
    - notebook
  imports:
    - start_jupyter_cm
  commands:
    - start_jupyter_cm --help
    - start_jupyter_cm --version
    - start_jupyter_cm
    - start_jupyter_cm --remove

about:
  home: https://github.com/hyperspy/start_jupyter_cm
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Add entries to start Jupyter from context menu.

extra:
  recipe-maintainers:
    - ericpre
    - francisco-dlp
