travis:
  secure:
    BINSTAR_TOKEN: PtELIhnISAWxCWkedNQSVSMrQB/+MG4lmv4UuJoWhE62QsfBDeuoP27rPThod8LMvGN1FGYp2x85yBNR4mdwQAvBEi9JZDN4Qc+haB0cCN8yQawPq8p7vlOhzlszKOqB6BWzrU2ZeEkUINZ/Tt6ZGL0T4JLKO1EHz/68FyVvH21aeYq8YX7oVDMIm/DbU3VS30lj/NiEyFFIBi7xAijm5aFUelXAgkuMQU2e8jbc5mT0yLvx8qrq1P4CwvRaZyfPEQho97iWM5h4kpvgY2kaNKTJDnkpBqnMRuNZOBPmtyDEUCMZ/Epvkr4igHzvaLA7JO4sCcwvyNPmeTnyYwk8YJJn5sr/Cfur6wjLD+OHLsgjiFX/Urvw3RU3h/jTY4AYPwfL5XDkviNNY+1GkZuByHUCpQsAEM2/wrVexXo8MMC1jWcAGRdHuk8pt5y8zP898WuP7nrVNHOzg2KIeDi6LmWtIx1maz59APpM5Ar/SxRpbkryLtobOPSm7sUP/9+s8Dyr1C9hwu/d/Zz5o4yg4CHuJHrfQlMAQoYD1k74Zm4vz4LWRooZDher4LAAmpsQ38IutjU6AS6wPV7nv97G3uUoJgs3/00aCKCHj0xbb+zu4TuEacrVjvcVh3q4WXh4xMHo+Ox/ptYH8toDDpXtPAJrjCwwyUv/CSnnLPZ3cq0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
